const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const ts = require('typescript');
require('ts-node').register({ project: join(__dirname, 'qa/tsconfig.qa.json'), transpileOnly: true });
require('tsconfig-paths').register({ baseUrl: join(__dirname, '..'), paths: { '@/*': ['./*'] } });
const utils = require('../lib/ktvUtils');
const source = readFileSync(join(__dirname, '../app/reception/dispatch/actions.ts'), 'utf8');
const body = source.slice(source.indexOf('export async function saveDispatchStaffRow('), source.indexOf('/**\n * Huỷ TOÀN BỘ đơn hàng.', source.indexOf('export async function saveDispatchStaffRow(')));
const code = ts.transpileModule(body, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const a = { id:'a', ktvId:'A', sequenceSlot:1, roomId:'R', bedId:'X', startTime:'10:00', endTime:'10:30', duration:30, actualStartTime:'2026-09-26T03:00:00Z' };
const b = { id:'b', ktvId:'B', sequenceSlot:2, roomId:'R', bedId:'X', startTime:'10:30', endTime:'11:00', duration:30 };
const item = { id:'item', status:'PREPARING', segments:[a,b], technicianCodes:['A','B'], roomName:'R', bedId:'X', options:{sequentialSlots:2,dispatchRevision:4,serviceNamesForKtvs:{A:'Tên A',B:'Tên B cũ'},notesForKtvs:{A:'Ghi chú A',B:'Ghi chú B cũ'}} };
let saved;
let persistDraft = false;
let enabledRevision;
let overlapPending = false;
const edits=[];
const notifications=[];
const db = { from(table) { return { select() { return this; }, eq() { return this; }, async single() { return { data: table === 'BookingItems' ? structuredClone(item) : { roomName:'R',bedId:'X',notes:'Giữ ghi chú đơn',bookingDate:'2026-09-26' } }; } }; } };
const deps = { requirePermission: async () => {}, getSupabaseAdmin: () => db, isTwoSlotSequential: require('../lib/dispatch-status').isTwoSlotSequential, parseKtvOptions:utils.parseKtvOptions,
  parseKtvSegments:utils.parseKtvSegments, ktvMetadataMap:utils.ktvMetadataMap,
  saveDraftDispatch: async (_booking, payload) => { saved = payload; if (persistDraft) { Object.assign(item,structuredClone(payload.itemUpdates[0])); item.options.dispatchRevision++; } return { success:true,savedItems:persistDraft ? [structuredClone(item)] : undefined,revisions:{item:persistDraft ? item.options.dispatchRevision : 5} }; },
  enableSequentialItem: async (_booking,_item,revision) => { enabledRevision=revision; return {success:true,revision:6}; },
  applyDispatchEdit: async (_db,_booking,action,payload) => {
    edits.push({action,payload});
    if(action==='ENABLE_SEQUENTIAL') { item.options={...item.options,sequentialSlots:2,dispatchRevision:5}; return {data:{success:true,revisions:{item:5}}}; }
    if (overlapPending && !payload.confirmOverlap) return {data:{success:false,code:'OVERLAP_CONFIRM_REQUIRED',overlapMinutes:15}};
    item.options.dispatchRevision=6;
    item.segments=[a,{...b,id:'server-b'}];
    return {data:{success:true,revisions:{item:6}}};
  },
  createNotification: async message => { notifications.push(message); return true; } };
const exportsStub = {};
new Function(...Object.keys(deps), 'exports', code)(...Object.values(deps), exportsStub);

(async () => {
  const editedB = { ktvId:'B', segments:[{...b,startTime:'10:45',endTime:'11:15'}], serviceNameForKtv:'Tên B mới', noteForKtv:'Ghi chú B mới' };
  assert.equal((await exportsStub.saveDispatchStaffRow('booking','item',editedB,4,true)).success,true);
  assert.deepEqual(saved.itemUpdates[0].segments[0],a);
  assert.equal(saved.itemUpdates[0].segments[1].startTime,'10:45');
  assert.deepEqual(saved.itemUpdates[0].options.serviceNamesForKtvs,{A:'Tên A',B:'Tên B mới'});
  assert.deepEqual(saved.itemUpdates[0].options.notesForKtvs,{A:'Ghi chú A',B:'Ghi chú B mới'});
  assert.equal(saved.notes,'Giữ ghi chú đơn');
  saved = null;
  assert.equal((await exportsStub.saveDispatchStaffRow('booking','item',editedB,3,true)).success,false);
  assert.equal(saved,null);
  item.segments[1].actualStartTime='2026-09-26T03:30:00Z';
  assert.equal((await exportsStub.saveDispatchStaffRow('booking','item',editedB,4,true)).success,true);
  assert.equal(saved.itemUpdates[0].segments[1].startTime,'10:30');
  assert.equal(saved.itemUpdates[0].segments[1].actualStartTime,item.segments[1].actualStartTime);
  item.status='NEW'; item.segments=[{...a,actualStartTime:undefined},{...a,id:'a2',startTime:'11:00',endTime:'11:30',actualStartTime:undefined},b];
  await exportsStub.saveDispatchStaffRow('booking','item',{ktvId:'A',segments:[{...item.segments[0],startTime:'10:15'},item.segments[1]],serviceNameForKtv:'A mới'},4,false);
  assert.equal(saved.itemUpdates[0].segments[0].startTime,'10:15');
  assert.deepEqual(saved.itemUpdates[0].segments[2],b);
  item.options={dispatchRevision:4}; item.segments=[{...b,sequenceSlot:undefined,actualStartTime:undefined}]; item.technicianCodes=['B'];
  const draftA={...a,actualStartTime:undefined};
  assert.equal((await exportsStub.saveDispatchStaffRow('booking','item',{ktvId:'A',segments:[draftA]},4,true)).success,true);
  assert.deepEqual(saved.itemUpdates[0].segments.map(s=>s.ktvId),['A']);
  assert.deepEqual(saved.itemUpdates[0].technicianCodes,['A']);
  item.status='PREPARING'; item.segments=[a]; item.options={dispatchRevision:4};
  const enabled=await exportsStub.saveDispatchStaffRow('booking','item',{ktvId:'A',segments:[{...a,sequenceSlot:1}]},4,true);
  assert.equal(enabled.success,true);
  assert.equal(saved.itemUpdates[0].options.sequentialSlots,undefined);
  assert.equal(enabledRevision,5);
  assert.equal(enabled.revisions.item,6);
  item.status='NEW'; item.options={dispatchRevision:9}; item.segments=[{...b,sequenceSlot:undefined,actualStartTime:undefined}]; saved=null;
  const rows=[{ktvId:'A',segments:[{...a,actualStartTime:undefined}],serviceNameForKtv:'A mới'},
    {ktvId:'B',segments:[b],serviceNameForKtv:'B mới'}];
  assert.equal((await exportsStub.saveSequentialPair('booking','item',rows,4,'Dịch vụ test')).success,true);
  assert.deepEqual(saved.itemUpdates[0].segments.map(s=>s.sequenceSlot),[1,2]);
  assert.deepEqual(saved.itemUpdates[0].technicianCodes,['A','B']);
  assert.equal(saved.itemUpdates[0].options.dispatchRevision,9);
  assert.equal(edits.length,0);
  item.status='IN_PROGRESS'; item.options={dispatchRevision:4}; item.segments=[a];
  const stalePair=await exportsStub.saveSequentialPair('booking','item',rows,3,'Dịch vụ test');
  assert.equal(stalePair.success,false);
  assert.equal(edits.length,0);
  const live=await exportsStub.saveSequentialPair('booking','item',rows,4,'Dịch vụ test');
  assert.equal(live.success,true);
  assert.deepEqual(edits.map(edit=>edit.action),['ENABLE_SEQUENTIAL','ASSIGN_B']);
  assert.equal(edits[1].payload.expectedRevision,5);
  assert.equal(live.revisions.item,6);
  assert.equal(live.savedSegments[1].id,'server-b');
  assert.equal(notifications.length,1);
  item.options={dispatchRevision:4}; item.segments=[a]; edits.length=0; overlapPending=true;
  const overlap=await exportsStub.saveSequentialPair('booking','item',rows,4,'Dịch vụ test');
  assert.equal(overlap.code,'OVERLAP_CONFIRM_REQUIRED');
  assert.equal(overlap.revisions.item,5);
  assert.deepEqual(item.segments,[a]);
  const retry=await exportsStub.saveSequentialPair('booking','item',rows,5,'Dịch vụ test',true);
  assert.equal(retry.success,true);
  assert.deepEqual(edits.map(edit=>edit.action),['ENABLE_SEQUENTIAL','ASSIGN_B','ASSIGN_B']);
  assert.equal(edits[2].payload.expectedRevision,5);
  // Exercise the official form action, including its authoritative response/revision.
  persistDraft=true; overlapPending=false; delete b.actualStartTime;
  item.status='NEW';item.options={dispatchRevision:0};item.segments=[];
  const first=await exportsStub.saveDispatchForm('booking','item',[rows[0]],0,true);
  assert.equal(first.success,true);assert.equal(first.revisions.item,1);
  assert.deepEqual(first.savedItem.segments.map(s=>s.ktvId),['A']);
  const pair=await exportsStub.saveDispatchForm('booking','item',rows,1,true);
  assert.equal(pair.success,true);assert.equal(pair.revisions.item,2);
  assert.deepEqual(pair.savedItem.segments.map(s=>s.ktvId),['A','B']);
  saved=null;
  assert.equal((await exportsStub.saveDispatchForm('booking','item',rows,1,true)).success,false);
  assert.equal(saved,null,'stale cached draft must not overwrite the DB');
  item.status='IN_PROGRESS';item.segments=[a,b];item.options={sequentialSlots:2,dispatchRevision:4};
  const edited=await exportsStub.saveDispatchForm('booking','item',[{ktvId:'A',segments:[a]},editedB],4,true);
  assert.equal(edited.success,true);assert.equal(edited.revisions.item,5);
  assert.deepEqual(edited.savedItem.segments[0],a);
  assert.equal(edited.savedItem.segments[1].startTime,'10:45');
  item.segments=[a,b];item.options={sequentialSlots:2,dispatchRevision:5};edits.length=0;
  const replacement=await exportsStub.saveDispatchForm('booking','item',[{ktvId:'A',segments:[a]},{ktvId:'C',segments:[{...b,id:'c',ktvId:'C'}]}],5,true);
  assert.equal(replacement.success,true);assert.deepEqual(edits,[],'full form uses one common commit instead of separate ASSIGN_B RPC');
  assert.deepEqual(saved.itemUpdates[0].technicianCodes,['A','C']);
  assert.equal(replacement.revisions.item,6);
  console.log('PASS official form action: draft A→A/B, stale draft rejection, live plan edit and B replacement');
  const page=readFileSync(join(__dirname,'../app/reception/dispatch/page.tsx'),'utf8');
  const guard=page.slice(page.indexOf('const confirmLeaveDraft ='),page.indexOf('  useEffect(() => {',page.indexOf('const confirmLeaveDraft =')));
  const navigation=new Function('dirtyRowsRef','dispatchPendingRef','queueSavingRef','queueDirtyRef','discardQueueRef','addToast','window',ts.transpileModule(guard+'return confirmLeaveDraft;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText);
  let prompts=0,allow=false;
  const dirtyRowsRef={current:new Set()};
  const dispatchPendingRef={current:false},queueSavingRef={current:false},queueDirtyRef={current:false},discardQueueRef={current:null};
  const confirmLeave=navigation(dirtyRowsRef,dispatchPendingRef,queueSavingRef,queueDirtyRef,discardQueueRef,()=>{},{confirm:()=>{prompts++;return allow;}});
  assert.equal(confirmLeave(),true);assert.equal(prompts,0);
  dirtyRowsRef.current.add('booking/item/A');
  assert.equal(confirmLeave(),false);allow=true;assert.equal(confirmLeave(),true);assert.equal(prompts,2);
  const unload=page.slice(page.indexOf('const warnOnRefresh ='),page.indexOf('    window.addEventListener',page.indexOf('const warnOnRefresh =')));
  const warn=new Function('dirtyRowsRef','queueDirtyRef','dispatchPendingRef','queueSavingRef',ts.transpileModule(unload+'return warnOnRefresh;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText)(dirtyRowsRef,queueDirtyRef,dispatchPendingRef,queueSavingRef);
  let prevented=false;const event={preventDefault(){prevented=true;},returnValue:null};
  warn(event);assert.equal(prevented,true);assert.equal(event.returnValue,'');
  console.log('PASS unsaved navigation: no prompt when clean, confirm on page switch, native guard on refresh');
  console.log('PASS per-KTV save keeps A, changes only B, rejects stale revision and preserves started B time');
})().catch(error => { console.error(error); process.exitCode = 1; });
